# Generated by Django 2.2 on 2021-10-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
